apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rate-scanning
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 9080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: 
       name: envoy.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          default_source_code:
            inline_string: |
              function envoy_on_request(request_handle)
                request_handle:logInfo("Request Log")
                request_handle:logInfo("Path: "..request_handle:headers():get(":path"))
              end          
              function envoy_on_response(response_handle)
                response_handle:logInfo("Response Log")
                response_handle:logInfo("Status: "..response_handle:headers():get(":status"))
              end